- name: Enable EPEL Repository on Rocky 8
  become: True
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'


- name: Update Package Cache (dnf/Rocky)
  tags: always
  become: yes
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Rocky"

