---
- name: Check if /root/ADMIN directory exists
  become: yes
  stat:
    path: '/root/ADMIN'
  register: admin_dir_exist

- debug: var=admin_dir_exist.stat.path

- name: Create /root/ADMIN directory if it doesn't already exist
  become: yes
  file:
    path: '/root/ADMIN'
    state: directory
    mode: 0755
    group: root
    owner: root
  when: not admin_dir_exist.stat.exists

## lua
## Download lua

# - name: Download lua {{lua_vers}} with check (sha256)
#   become: yes
#   get_url:
#     url: https://www.lua.org/ftp/lua-{{lua_vers}}.tar.gz
#     dest: /root/ADMIN/lua-{{lua_vers}}.tar.gz
#     checksum: sha256:fc5fd69bb8736323f026672b1b7235da613d7177e72558893a0bdcd320466d60

# ## Install lua 

# #- name: Install readline-dev
# #  dnf:
# #    name: readline-dev
# #    state: latest

# - name: Install lua {{lua_vers}}
#   become: yes
#   tags: lua_install
#   shell: |
#      cd  /root/ADMIN/
#      tar -zxvf lua-{{lua_vers}}.tar.gz
#      cd lua-{{lua_vers}}
#      make linux
#      make test && make install
#      ln -s /usr/local/bin/lua /usr/bin/
#      ln -s /usr/local/bin/luac /usr/bin/
#      #echo "Hello! I got into the unpacked dir! Here are the contents $(ls -l )"
#   register: lua_install

# - debug: 
#     var: lua_install.stdout_lines

### luarocks Install
## Install luarocks deps

- name: Install luarocks dependency packages
  become: yes
  register: luarocks_deps
  apt:
    update_cache: yes
    name:
      - build-essential
      - libreadline-dev 
      - unzip
    state: present
- debug:
    var: luarocks_deps.stdout_lines

## Download luarocks

- name: Download luarocks release {{luarocks_vers}}
  become: yes
  get_url:
    url: https://luarocks.org/releases/luarocks-{{luarocks_vers}}.tar.gz
    dest: /root/ADMIN/luarocks-{{luarocks_vers}}.tar.gz

## Install luarocks

- name: Install luarocks
  become: yes
  tags: luarocks_install
  shell: |
     cd  /root/ADMIN/
     tar -zxvf luarocks-{{luarocks_vers}}.tar.gz
     cd luarocks-{{luarocks_vers}}
     ./configure --with-lua-include=/usr/local/include
     make && sudo make install
     #echo "Hello! I got into the unpacked dir! Here are the contents $(ls -l )"
  register: luarocks_install

- debug: 
    var: luarocks_install.stdout_lines

# ## Install luaposix

# - name: Install luaposix
#   become: yes
#   tags: luaposix_install
#   shell: luarocks install luaposix
#   register: luaposix_install

# - debug: 
#     var: luaposix_install.stdout_lines

# ## Install luafilesystem 

# - name: Install luafilesystem
#   become: yes
#   tags: luafilesystem_install
#   shell: luarocks install luafilesystem
#   register: luafilesystem_install

# - debug: 
#     var: luafilesystem_install.stdout_lines